### ISSUE TITLE
Invalid URL for 'exmaple project' in README.md

### ISSUE THREAD

**Issue by ykh** [lucasrochagit/nest-mongo-query-parser#11]
Hi,
thanks for develop such a useful tool.
In the README.md there is a link to example project which is not valid (getting 404).
What I'm looking for, how to use the parsed query directly in Mongoose? Is there any guide for this?
Thanks in advanced.

**Comment by lucasrochagit** [comment]
Hello, @ykh! 

I'm glad the tool was useful for you.

Yes, unfortunately I disabled the example project referred on README.md. But I have an example of a project that uses the library. Here is the link to access it: https://github.com/lucasrochagit/template-nestjs-with-mongodb. I intend to keep updating this project, and I intend to use it as a reference for using the library, so I will update the README.md soon.

Please check [the user service](https://github.com/lucasrochagit/template-nestjs-with-mongodb/blob/main/src/user/user.service.ts) file, and see the `find()` method in the line 19. There's a quite example of how use the library object `MongoQueryModel` into find schema method, using the mongoose build pattern. 

If you still have questions, don't hesitate to ask.

Best regards,
