### ISSUE TITLE
QueryObjectModel import statement

### ISSUE THREAD

**Issue by DocAmaroo** [lucasrochagit/nest-mongo-query-parser#7]
### Description

I discover that the `QueryObjectModel` was not exported in the model `index.ts` and ended up having multiple import statement:

```
// model/index.ts
export { MongoQueryModel } from './mongo.query.model';
```

and it ended up causing import statement has below in my code:

```
// import statement in my code
import { MongoQueryModel } from 'nest-mongo-query-parser';
import { QueryObjectModel } from 'nest-mongo-query-parser/dist/lib/model/mongo.query.model';
```

There is maybe a reason for that.

### Alternative/Solutions

If it's possible, it would be great to export the `QueryObjectModel` next to the `MongoQueryModel` and simplify the import statement.

**Comment by lucasrochagit** [comment]
For sure, man. Btw sorry for the delay in responding you. I will provide this.
